/** Service records join aircraft and personnel through finalized sortie identities. */
import { CREW_DEFS } from './board.mjs';
import { targetChoiceMarkup } from './bomb-run-view.mjs';
import { bombingOutcomeLabel } from './bombing.mjs';
import { aircraftServiceRecord, aircraftStatus, crewServiceRecord, campaignOverview } from './campaign.mjs';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleName = role => CREW_DEFS.find(c => c.id === role)?.name ?? role;
const dateLabel = date => new Date(date).toLocaleDateString();
const count = (label, value) => `<span><small>${label}</small><b>${value}</b></span>`;
const targetName = sortie => sortie.bombing.target?.name ?? (typeof sortie.target === 'string' ? sortie.target : sortie.target?.name) ?? 'Target';
const objectiveLabel = sortie => sortie.objectiveResult === 'aborted' ? 'MISSION ABORTED'
  : sortie.objectiveResult === 'achieved' ? 'OBJECTIVE ACHIEVED' : 'OBJECTIVE FAILED';
const aircraftLink = (campaign, id) => `<button type="button" class="service-link" data-service-aircraft="${esc(id)}">${esc(campaign.aircraft.find(a => a.id === id)?.name)}</button>`;
const crewLink = (campaign, id) => `<button type="button" class="service-link" data-service-personnel="${esc(id)}">${esc(campaign.crew.find(c => c.id === id)?.name)}</button>`;
const lossReason = sortie => typeof sortie.reason === 'string' ? sortie.reason : sortie.reason?.cause === 'structure'
  ? `Structural failure — ${sortie.reason.compromisedSections ?? sortie.finalCompromisedSections.length} compromised sections`
  : sortie.reason?.detail ?? (sortie.reason?.cause === 'altitude' ? 'Altitude lost — aircraft reached the ground' : sortie.reason?.cause ?? 'Aircraft destroyed');

export function campaignMarkup(store, state) {
  const campaign = store.campaigns.find(c => c.id === store.activeCampaignId);
  const controls = `<div class="campaign-controls"><button data-ui="campaign-new" class="primary">New Campaign</button><button data-ui="campaign-export" class="quiet">Campaign Export JSON</button><label class="campaign-import">Campaign Import JSON<input type="file" id="campaign-import" accept="application/json,.json"></label></div>`;
  if (!campaign) return `<p>Build a Hangar of named aircraft and keep their crew service records across V2 sorties. Every flight starts with healthy crew and a repaired aircraft.</p>${controls}`;
  const matching = Boolean(campaign.activeSortie && state.campaign?.campaignId === campaign.id && state.campaign?.sortieId === campaign.activeSortie.sortieId && !state.outcome);
  const unavailable = Boolean(campaign.activeSortie) && !matching;
  const stats = campaignOverview(campaign);
  const available = campaign.aircraft.filter(a => aircraftStatus(campaign, a.id) === 'available')
    .sort((a, b) => (aircraftServiceRecord(campaign, b.id).lastSortie?.number ?? 0) - (aircraftServiceRecord(campaign, a.id).lastSortie?.number ?? 0));
  const lost = campaign.aircraft.filter(a => a.lost).sort((a, b) => b.lostOnMission - a.lostOnMission);
  const flying = campaign.aircraft.filter(a => aircraftStatus(campaign, a.id) === 'on-sortie');
  return `${controls}<label>Campaign<select id="campaign-select">${store.campaigns.map(c => `<option value="${esc(c.id)}" ${c.id === campaign.id ? 'selected' : ''}>${esc(c.name)}</option>`).join('')}</select></label>
    <section class="service-record"><div class="eyebrow">CAMPAIGN OVERVIEW · EST. ${esc(dateLabel(campaign.createdAt))}</div><h3>${esc(campaign.name)}</h3>
    <div class="service-totals">${count('Aircraft commissioned', stats.totalAircraft)}${count('Available aircraft', stats.availableAircraft)}${count('On sortie', stats.aircraftOnSortie)}${count('Aircraft lost', stats.planesLost)}${count('Crew identities', stats.totalCrew)}${count('Living crew', stats.livingCrew)}${count('Crew KIA', stats.crewKIA)}${count('Sorties', stats.totalSorties)}${count('Objectives achieved', stats.objectivesAchieved)}${count('Objectives failed', stats.objectivesFailed)}${count('Aborted missions', stats.abortedMissions)}${count('Aircraft returned', stats.aircraftReturned)}${count('Fighters destroyed', stats.fightersDestroyed)}${count('Bombing score', stats.cumulativeBombingScore)}</div>
    <p class="small">Bombing results: ${Object.entries(stats.bombingOutcomes).map(([outcome, total]) => `${esc(bombingOutcomeLabel(outcome))} ${total}`).join(' · ') || 'None yet'}</p>
    <p class="small">History only: no XP, upgrades, persistent wounds, damage or gameplay advantages. Any scored target damage achieves the objective; Miss and No Drop fail it. Returning HOME is recorded separately.</p>
    ${matching ? '<button data-ui="campaign-resume" class="primary">Continue Campaign · resume sortie →</button>' : unavailable ? '<p class="action-error">This campaign has an unfinished sortie. Import its campaign backup with active sortie to resume it.</p>' : ''}</section>
    <section class="service-record campaign-hangar"><div class="eyebrow">CAMPAIGN HANGAR</div><h3>Available Aircraft</h3>
    ${available.length ? `<div class="hangar-list">${available.map(a => aircraftCard(a, campaign)).join('')}</div>` : '<p class="replacement-note">No aircraft available. Commission New Aircraft to prepare your next sortie.</p>'}
    ${flying.length ? `<h3>Currently on sortie</h3>${flying.map(a => aircraftCard(a, campaign)).join('')}` : ''}
    <details class="commission-panel"><summary>Commission New Aircraft</summary><p class="small">Add another B-17 to your Hangar. Existing aircraft and their service records stay with the squadron.</p><form id="campaign-commission-form"><label>Aircraft name<input name="name" value="Untitled B-17 ${campaign.aircraft.length + 1}" maxlength="80" required></label><label>Serial / call sign<input name="serial" maxlength="80"></label><button class="primary" type="submit">Commission New Aircraft</button></form></details>
    ${!campaign.activeSortie && available.length ? `<form id="campaign-launch-form"><h3>Next Campaign Sortie</h3><p class="small">Select an available aircraft above for each new sortie. The current ten-role crew roster flies with your choice; KIA roles receive new personnel identities.</p><label>RNG seed<input name="seed" value="CAMPAIGN-${campaign.sorties.length + 1}" maxlength="100" required></label>${targetChoiceMarkup()}<button class="primary" type="submit">Fly selected aircraft · sortie ${campaign.sorties.length + 1} →</button></form>` : ''}
    <h3>Lost Aircraft · Memorial</h3><div class="hangar-list lost-aircraft">${lost.length ? lost.map(a => aircraftCard(a, campaign)).join('') : '<p>No aircraft lost.</p>'}</div></section>
    <section class="service-record"><h3>Crew Roster</h3><p class="small">One shared ten-role roster, independent of aircraft. Surviving crew retain their identities on every flight.</p><div class="personnel-list">${Object.values(campaign.roster).map(id => campaign.crew.find(c => c.id === id)).filter(c => !c.kia).map(c => crewCard(c, campaign)).join('')}</div>${Object.values(campaign.roster).some(id => campaign.crew.find(c => c.id === id).kia) ? '<p class="replacement-note">Fallen crew are remembered below. New replacement identities fill their roles at the next launch.</p>' : ''}</section>
    <section class="service-record"><h3>Sortie History</h3>${campaign.sorties.length ? campaign.sorties.slice().reverse().map(sortie => sortieCard(sortie, campaign)).join('') : '<p>No sorties recorded yet.</p>'}</section>
    ${campaign.crew.some(c => c.kia) ? `<details class="service-record personnel-archive"><summary>Personnel archive · fallen crew</summary>${campaign.crew.filter(c => c.kia).map(c => crewCard(c, campaign)).join('')}</details>` : ''}`;
}

function aircraftCard(aircraft, campaign) {
  const service = aircraftServiceRecord(campaign, aircraft.id), last = service.lastSortie;
  const status = { available: 'AVAILABLE', 'on-sortie': 'CURRENTLY ON SORTIE', lost: 'AIRCRAFT LOST' }[service.status];
  return `<article class="hangar-card ${aircraft.lost ? 'lost' : ''}" data-aircraft-card="${esc(aircraft.id)}"><div class="eyebrow">${status}</div><h4>${esc(aircraft.name)}</h4>${aircraft.serial ? `<p class="small">${esc(aircraft.serial)}</p>` : ''}
    <p class="small">${aircraft.missionsFlown} missions · ${aircraft.fightersDestroyed} fighters destroyed · ${service.crewLosses} crew KIA aboard<br>${aircraft.missionsSurvived} returned · ${aircraft.missionsAborted} aborted · ${aircraft.bombingHistory.filter(b => b.status === 'committed').length} bomb runs</p>
    <p class="small">Last sortie: ${last ? `#${last.number} · ${esc(targetName(last))} · ${esc(last.result)} · ${objectiveLabel(last)}${last.bombing.outcome ? ' · ' + esc(bombingOutcomeLabel(last.bombing.outcome)) : ''}` : 'Not yet flown'}</p>
    ${!campaign.activeSortie && service.status === 'available' ? `<label class="aircraft-choice"><input type="radio" name="aircraftId" value="${esc(aircraft.id)}" form="campaign-launch-form" required> Select for next sortie</label>` : ''}
    <details class="aircraft-service" data-aircraft-service="${esc(aircraft.id)}"><summary>View Service Record</summary><p class="small">Commissioned ${esc(dateLabel(aircraft.createdAt))} · ${aircraft.timesDamaged} aircraft hits recorded</p>
    ${service.loss ? `<p class="loss-record"><b>AIRCRAFT LOST · Sortie ${service.loss.number} · ${esc(targetName(service.loss))}</b><br>${esc(lossReason(service.loss))}<br>Final altitude ${service.loss.finalAltitude} · ${service.loss.finalCompromisedSections.length} compromised sections${service.loss.finalCompromisedSections.length ? ': ' + service.loss.finalCompromisedSections.map(esc).join(', ') : ''} · ${service.loss.enginesLost} engines lost · ${service.loss.aircraftHits} aircraft hits</p>` : ''}
    <h5>Bombing record</h5>${aircraft.bombingHistory.length ? `<ul>${aircraft.bombingHistory.map(b => `<li>Sortie ${b.number} · ${esc(b.target?.name ?? b.target ?? 'Target')} — ${esc(bombingOutcomeLabel(b.outcome))}${b.score !== null ? ` · ${b.score}/9 · Dice ${b.dice.join(' / ')}` : ''}</li>`).join('')}</ul>` : '<p class="small">No bombing results recorded.</p>'}
    <h5>Crew who served aboard</h5>${service.crew.length ? `<ul>${service.crew.map(entry => `<li>${crewLink(campaign, entry.crewId)} · ${entry.missions} sorties · ${entry.fighterKills} kills${campaign.crew.find(c => c.id === entry.crewId).kia ? ' · KIA' : ''}</li>`).join('')}</ul>` : '<p class="small">No crew service recorded yet.</p>'}
    <h5>Sortie History</h5>${service.sorties.map(sortie => sortieCard(sortie, campaign)).join('') || '<p class="small">Not yet flown.</p>'}</details>
    ${aircraft.lost ? '' : `<details class="aircraft-edit"><summary>Rename / Edit</summary><form class="aircraft-record" data-aircraft-rename="${esc(aircraft.id)}" data-campaign-id="${esc(campaign.id)}"><label>Aircraft name<input name="name" value="${esc(aircraft.name)}" maxlength="80" required></label><label>Serial / call sign<input name="serial" value="${esc(aircraft.serial)}" maxlength="80"></label><button type="submit" class="quiet">Save aircraft name</button></form></details>`}</article>`;
}
function crewCard(crew, campaign) {
  const service = crewServiceRecord(campaign, crew.id);
  return `<details class="personnel-card ${crew.kia ? 'kia' : ''}" data-personnel-service="${esc(crew.id)}"><summary><b>${esc(crew.name)}</b><span>${esc(roleName(crew.role))} · ${crew.kia ? 'KIA' : crew.replacement ? 'REPLACEMENT' : 'SERVING'}</span></summary><form data-crew-rename="${esc(crew.id)}" data-campaign-id="${esc(campaign.id)}"><label>Personnel name<input name="name" value="${esc(crew.name)}" maxlength="80" required></label><button type="submit" class="quiet">Save crew name</button></form><p class="small">${crew.missionsFlown} missions · ${crew.fighterKills} fighter kills · ${crew.woundsSuffered} wounds<br>Jobs: ${crew.jobsCompleted.repair} Repair · ${crew.jobsCompleted.fireControl} Fire Control · ${crew.jobsCompleted.medical} Medical</p>${crew.kia ? `<p>KIA on sortie ${crew.killedOnMission} aboard ${aircraftLink(campaign, crew.killedOnAircraftId)}. Identity retained permanently.</p>` : ''}<h5>Aircraft served aboard</h5><ul>${service.aircraft.map(entry => `<li>${aircraftLink(campaign, entry.aircraftId)} · ${entry.missions} sorties · ${entry.fighterKills} kills</li>`).join('') || '<li>Not yet flown.</li>'}</ul>${crew.history.length ? `<p class="small">${crew.history.map(h => `Sortie ${h.number}: ${esc(h.health)}`).join(' · ')}</p>` : ''}</details>`;
}
function sortieCard(sortie, campaign) {
  return `<details class="sortie-history-card"><summary><b>#${sortie.number} · ${esc(sortie.result)}</b><span>${objectiveLabel(sortie)} · ${esc(targetName(sortie))} · ${esc(dateLabel(sortie.date))}</span></summary><p>Aircraft: ${aircraftLink(campaign, sortie.aircraftId)}<br>Seed: <b>${esc(sortie.seed)}</b></p><p>${sortie.bombing.score !== null ? `Bombing ${sortie.bombing.score}/9 · ${esc(bombingOutcomeLabel(sortie.bombing.outcome))}` : esc(sortie.aborted ? 'ABORTED — NO BOMBING CREDIT' : sortie.bombing.outcome ? bombingOutcomeLabel(sortie.bombing.outcome) : 'No drop recorded')}</p>${!sortie.aircraftSurvived ? `<p>${esc(lossReason(sortie))}</p>` : ''}<p class="small">Dice: ${sortie.bombing.dice.join(' · ') || 'No drop'}<br>${sortie.fightersDestroyed} fighters destroyed · Progress ${sortie.progressReached} · Altitude ${sortie.finalAltitude} · ${sortie.finalCompromisedSections.length} compromised sections · ${sortie.enginesLost} engines lost</p><p class="small">${sortie.crewOutcomes.map(c => `${crewLink(campaign, c.id)} (${esc(roleName(c.role))}): ${esc(c.health)}`).join(' · ')}</p><details><summary>Sortie snapshot</summary><pre class="campaign-snapshot">${esc(JSON.stringify(sortie, null, 2))}</pre></details></details>`;
}
